# Generated by Django 5.0 on 2025-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_image_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='positionDetail',
            field=models.TextField(),
        ),
    ]
