# Generated by Django 5.0 on 2025-01-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_positiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
